version: '3.4'
services:
    goerli.avadobox.eth:
        image: 'goerli.avadobox.eth:0.1.8'
        build: ./build
        volumes:
            - 'goerli:/goerli'
        environment: 
            - EXTRA_OPTS=
        ports:
            - '80:80'
            - '8546:8546'
            - '8545:8545'
            - '53535:30303'
            - '53535:30303/udp'
            - '53534:30304/udp'
volumes:
    goerli: {}
